### ISSUE TITLE
Cannot read from stdin

### ISSUE THREAD

**Issue by siebz0r** [gforcada/flake8-pep3101#15]
It seems that I cannot lint a file passed to flake8 using stdin.

Steps to reproduce:

```sh
$ virtualenv -p python2.7 /tmp/venv-$RANDOM
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /tmp/venv-15675/bin/python2.7
Also creating executable in /tmp/venv-15675/bin/python
Installing setuptools, pip, wheel...done.

$ source /tmp/venv-15675/bin/activate

(venv-15675) $ pip install flake8-pep3101==1.0
Collecting flake8-pep3101==1.0
Collecting flake8>=3.0 (from flake8-pep3101==1.0)
  Using cached flake8-3.3.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from flake8>=3.0->flake8-pep3101==1.0)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting configparser; python_version < "3.2" (from flake8>=3.0->flake8-pep3101==1.0)
Collecting pyflakes<1.6.0,>=1.5.0 (from flake8>=3.0->flake8-pep3101==1.0)
  Using cached pyflakes-1.5.0-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8>=3.0->flake8-pep3101==1.0)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8>=3.0->flake8-pep3101==1.0)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Installing collected packages: enum34, configparser, pyflakes, mccabe, pycodestyle, flake8, flake8-pep3101
Successfully installed configparser-3.5.0 enum34-1.1.6 flake8-3.3.0 flake8-pep3101-1.0 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.5.0

(venv-15675) $ touch a.py

(venv-15675) $ cat a.py| flake8 -
Traceback (most recent call last):
  File "/tmp/venv-15675/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/tmp/venv-15675/lib/python2.7/site-packages/flake8_pep3101.py", line 19, in run
    tree = ast.parse(lines)
  File "/usr/lib64/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
TypeError: expected a readable buffer object
```

On Python 3.5 it also doesn't work:

```sh
Traceback (most recent call last):
  File "/tmp/venv-19888/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/main/application.py", line 316, in _run
    self.run_checks()
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/main/application.py", line 246, in run_checks
    self.file_checker_manager.run()
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/checker.py", line 319, in run
    self.run_serial()
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/checker.py", line 303, in run_serial
    checker.run_checks()
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8/checker.py", line 487, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/tmp/venv-19888/lib/python3.5/site-packages/flake8_pep3101.py", line 19, in run
    tree = ast.parse(lines)
  File "/usr/lib64/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
TypeError: compile() arg 1 must be a string, bytes or AST object
```

When using 0.6 it does seem to work, but I would like to be able to use the latest and greatest.

**Comment by siebz0r** [comment]
Of course after reporting this I see that this has already been fixed in #14. So let's pretend this never happend :grimacing:.
